[project]
name = "agentkit-skill-sandbox-samples"
version = "0.1.0"
description = "agentkit skills sandbox samples with veadk-0.x.x"
readme = "README.md"
requires-python = ">=3.12,<3.14"
dependencies = [
    "agentkit-sdk-python==0.8.1",
    "google-adk==2.2.0",
    "urllib3<2.0.0",
    "litellm",
    "veadk-python==1.0.10",
    "volcengine-python-sdk>=4.0.33",
]
