export const products = {
 en: {
 lang:'en', home:'/', path:'/products/estate-studio/', alternate:'/zh/products/estate-studio/', language:'中文', homeLabel:'Home', productLabel:'Product',
 title:'Estate Studio — AI Property Marketing Content Software', description:'Explore Estate Studio for property teams: organise project information and prepare interactive tours, sales materials and marketing content.',
 eyebrow:'The product / Estate Studio', h1:'AI content studio<br>for property teams.', intro:'Estate Studio helps property teams organise project information and prepare interactive tours, sales materials and marketing creative. Start with floor plans, imagery and brand assets, then review your content against confirmed information before delivery.',
 explore:'Explore the features', contact:'Request a demo', contents:'On this page', labels:['Overview','Who it’s for','Features','What you need','How it works','Example workflows','FAQ'],
 visualTitle:'One project. Connected outputs.', visualNote:'Workflow illustration · AI concept imagery', outputLabels:['Project information','Room presentation','Sales materials','Marketing creative'],
 overviewTitle:'What is Estate Studio?', overview:['Estate Studio is a project-centred content workspace for developers, project marketers, real-estate agencies and property creative studios. It connects the information behind a development with the materials a team needs to explain and promote it.','The project is the starting point. Floor plans, imagery, brand guidelines and confirmed facts provide context for each new content task. A sales sheet can build on the same information as a room presentation, while a campaign can continue an established visual direction.','The aim is a repeatable preparation, creation and review process. Buyers get material that helps them understand a space; sales teams get information they can explain; creative teams have an organised starting point for their next revision. These are intended uses, not a promise of particular sales results.'],
 audienceTitle:'Who is Estate Studio for?', audiences:[['Developers & project marketers','Prepare multiple pieces of content around one development. Keep project facts and brand direction available as you review new work.'],['Real-estate agencies','Explain a unit through room imagery and supporting sales information. Choose material appropriate to the conversation with your buyer.'],['Property creative studios','Organise work around separate client projects and keep source information with the output, making later revisions and handover easier to follow.']],
 featuresTitle:'What can you create?', featuresIntro:'Five connected parts of a property content workflow. Each starts with project information and ends with work your team can review.',
 features:[
 ['Project information','Prepare a shared starting point.','Organise floor plans, imagery, brand files and confirmed project facts before creating content. Identify missing information and distinguish official material from concepts, so the next task starts with useful context.','Input: project files and confirmed facts. Output: organised information for content tasks.'],
 ['Interactive tour content','Help buyers understand the space.','Connect room views with floor-plan information to explain how a property is arranged. Depending on the available assets and completed work, a presentation may include stills, panoramas or a reviewed tour. The images on this page illustrate room content; they are not a complete navigable or measured 3D model.','Input: plans and reviewed room assets. Output: spatial presentation content.'],
 ['Sales materials','Turn facts into a clear presentation.','Prepare project brochures, floor plan books and unit sales sheets from confirmed information. Review the facts alongside the layout before sharing. A design example is not evidence that prices, specifications or availability have been approved.','Input: approved information and imagery. Output: sales-document content and layouts.'],
 ['Marketing creative','Continue the same brand story.','Prepare posters and promotional material around the project’s visual guidelines. Reuse suitable imagery and established information as a starting point. Completed outputs and concept examples should be labelled clearly so the team knows what is ready to review.','Input: brand assets and project brief. Output: campaign concepts and marketing materials.'],
 ['Review & handover','Keep the context with the work.','Check factual claims, visual details and brand expression before arranging delivery. Keep sources and versions alongside the output so a reviewer can understand its basis and another team member can continue the work. Actual export or publishing arrangements depend on the project workflow.','Input: created work and its sources. Output: reviewed material and an organised handover.']
 ],
 inputsTitle:'What do you need to get started?', inputsIntro:'Start with the information you already have, then identify what the intended output still needs. A first conversation does not require uploading project files.', inputs:[['Floor plans','Confirm rooms, layout and the limits of the space being presented.'],['Project facts','Use confirmed descriptions and unit information as the basis for claims.'],['Imagery & references','Identify the source, permitted use and review status of each asset.'],['Brand guidelines','Bring your logo, colours, type choices and existing visual direction.'],['A content goal','Choose the first output and explain who will use it and where.']],
 workflowTitle:'How does the workflow work?', steps:[['Organise the project','Collect the plans, project information and brand files. Identify the unit or development the work is about.'],['Confirm the basis','Check key facts and note missing information. Agree which assets can be used for the intended presentation.'],['Choose a task','Prepare a tour, sales document or marketing asset around the existing project context.'],['Review the result','Check factual details, spatial representation and branding. Resolve issues before calling an output ready.'],['Arrange delivery','Export or publish through the available project workflow. Keep drafts distinct from approved deliverables.']],
 scenariosTitle:'Two ways a team might use Estate Studio', scenarios:[['Explain a single apartment','Start with a confirmed floor plan and room imagery. Prepare a room presentation and a unit sales sheet, giving the buyer a way to see the space and the sales team a way to discuss its details.','A workflow example, not a named customer result.'],['Refresh a project campaign','Use existing brand guidelines and reviewed imagery as the starting point for a new poster. Check the latest project information and visual expression before preparing it for its intended channel.','Review current facts before reusing earlier material.']],
 faqTitle:'Frequently asked questions', faqs:[['What is Estate Studio?','A project-centred AI content workspace for property teams preparing and reviewing interactive tour content, sales materials and marketing creative.'],['What can I create with it?','The product workflow covers room and tour presentation content, sales documents and marketing creative. Discuss your intended output in a demo to understand the capabilities and support currently available.'],['Can I start with only a floor plan?','A floor plan can be a starting point for assessing the task and missing information. A complete presentation may need additional imagery, brand assets and confirmed project details.'],['Is a room image preview a full interactive tour?','No. A still-image preview shows individual room concepts. A complete tour needs its own reviewed assets and navigation; its available behaviour should be demonstrated separately.'],['Do AI visuals represent the finished property?','AI visuals are conceptual. They need review against formal project documents and appropriate disclosures. They do not establish final specifications or built conditions.'],['Do I need to install software to read this product page?','No. This product introduction is accessible directly in a desktop, tablet or mobile browser.'],['How do I learn about pricing and access?','Email hello@estatestudio.io with your project type and the content you want to prepare. Available access, production support and services can be discussed around that requirement.'],['Does clicking the demo link book a meeting?','The link opens your email application. Review and send the message yourself; clicking the link does not confirm receipt or schedule a meeting.']],
 contactTitle:'Let’s talk about your project.', contactBody:'Tell us what you’re preparing and who it’s for. Explore how Estate Studio could fit into the work.', contactNote:'Opens your email app. No files or registration needed.', footer:'Project information. Thoughtful content. Reviewed delivery.', concept:'AI concept imagery. Not a verified property specification.', back:'Back to top', skip:'Skip to product information', inputLabel:'The starting point', outputLabel:'The possibilities',
 },
 zh: {
 lang:'zh-CN', home:'/zh/', path:'/zh/products/estate-studio/', alternate:'/products/estate-studio/', language:'EN', homeLabel:'首页', productLabel:'产品介绍',
 title:'Estate Studio 产品介绍｜地产 AI 内容制作工具', description:'了解 Estate Studio 如何帮助地产团队整理项目资料，制作互动导览、销售资料与营销创意。查看功能、适用场景、所需资料与工作流程。',
 eyebrow:'产品介绍 / Estate Studio', h1:'地产团队的<br>AI 内容工作室。', intro:'Estate Studio 帮助地产团队整理项目资料，准备互动导览、销售资料与营销创意。以户型图、项目图片和品牌素材为基础，让不同制作任务沿用同一份项目背景，并在交付前核对内容与已确认的信息。',
 explore:'查看产品功能', contact:'联系演示', contents:'本页内容', labels:['产品概述','适合谁','核心功能','所需资料','使用流程','应用场景','常见问题'],
 visualTitle:'一个项目，连接不同成果。', visualNote:'工作流程示意 · AI 概念画面', outputLabels:['项目资料','房间展示','销售资料','营销创意'],
 overviewTitle:'Estate Studio 是什么？', overview:['Estate Studio 是面向开发商、项目营销团队、地产代理及创意工作室的项目内容工作空间。它把地产项目背后的信息，与团队需要用来说明和推广项目的内容连接起来。','每个制作任务都从项目资料开始。户型图、图片、品牌规范和已确认的事实，为下一份内容提供基础。销售页可以沿用房间展示使用的信息，推广海报也可以延续既有的视觉方向。','团队围绕资料整理、内容制作和成果审阅推进工作：买家获得帮助理解空间的内容，销售人员有可以解释的资料，创意团队能从已有项目继续修改。这些是使用目的，不代表对成交率或效率的量化承诺。'],
 audienceTitle:'哪些团队适合使用？', audiences:[['开发商与项目营销团队','围绕同一楼盘持续准备多种展示内容。在审阅新成果时，沿用已经整理好的项目信息和品牌方向。'],['地产代理机构','结合房间画面与销售资料介绍户型，选择适合当前客户沟通场景的内容，让空间和信息更容易解释。'],['地产创意工作室','按客户项目组织工作，将来源资料和成果保留在一起，方便后续修改，也让交接更容易理解。']],
 featuresTitle:'可以制作什么？', featuresIntro:'从项目资料出发，连接五个内容工作环节。每项成果都需要你的团队核对与审阅。',
 features:[
 ['项目资料组织','为下一次创作准备基础。','先整理户型图、图片、品牌文件和已确认的项目信息，再开展内容制作。明确缺少哪些资料，区分官方文件与概念素材，让后续任务能够从已有背景继续。','输入：项目文件与已确认事实。输出：可用于内容任务的项目资料。'],
 ['互动导览内容','让客户更容易理解空间。','结合房间画面与户型信息说明空间关系。根据项目资料和成果完成状态，可以准备图片、全景或经过审阅的导览内容。本页中的图片用于说明房间内容，不是完整可导航的导览，也不是测量级三维模型。','输入：户型资料与经审阅的房间素材。输出：空间展示内容。'],
 ['销售资料','把项目信息整理成清晰的表达。','使用已确认的信息准备项目画册、户型图册和单户型销售页。分享之前，需要同时审阅事实和版式。设计示意不能证明其中的价格、规格或房源状态已获准对外发布。','输入：已确认信息与图片。输出：销售文档内容及版式。'],
 ['营销创意','让不同素材延续同一个品牌。','围绕项目视觉规范准备海报与推广内容。从可用图片和已有信息开始，延续既定的品牌方向。已完成成果与概念样例应有明确标识，帮助团队判断下一步需要审阅什么。','输入：品牌素材与项目需求。输出：推广创意与营销素材。'],
 ['审阅与交接','把内容依据留在成果旁边。','交付前核对事实、画面细节和品牌表达。将资料来源与版本和成果一起整理，让审阅者知道内容从哪里来，也方便其他成员继续工作。具体导出或发布方式按实际项目流程安排。','输入：创作成果及来源资料。输出：经审阅内容与可交接文件。']
 ],
 inputsTitle:'开始需要准备哪些资料？', inputsIntro:'从手头已有资料开始，再根据希望制作的成果梳理缺口。首次联系演示不需要上传项目文件。', inputs:[['户型与空间资料','用于确认房间、布局及需要展示的空间范围。'],['项目事实','以已确认的项目描述和户型信息作为对外表达依据。'],['图片与参考素材','说明每份素材的来源、使用范围和审阅状态。'],['品牌规范','准备 Logo、颜色、字体及已有设计方向。'],['内容目标','明确先制作什么、给谁看，以及用于哪种沟通场景。']],
 workflowTitle:'如何开展一次内容制作？', steps:[['整理项目','收集户型图、项目信息与品牌文件，明确任务对应的楼盘或户型。'],['确认依据','核对关键事实并记录资料缺口，确认哪些素材可用于这次展示。'],['选择任务','围绕已有项目资料，准备导览、销售文档或营销内容。'],['审阅成果','检查事实、空间表达与品牌一致性，解决问题后再确认可交付状态。'],['安排交付','按实际可用方式导出或发布，保留草稿与已确认成果的区别。']],
 scenariosTitle:'两种具体的使用方式', scenarios:[['介绍一个户型','从已确认的户型图和房间画面开始，准备房间展示与单户型销售页。客户有内容可以看，销售人员也有资料可以用来解释关键信息。','这是任务流程示例，不是具名客户成果。'],['更新项目推广内容','以已有品牌规范和经审阅图片为起点准备新海报。交付给目标渠道前，检查最新项目信息以及整体视觉表达。','复用旧素材时，仍需核对当前事实。']],
 faqTitle:'常见问题', faqs:[['Estate Studio 是什么？','一个以项目为中心的 AI 内容工作空间，帮助地产团队准备和审阅互动导览内容、销售资料与营销创意。'],['可以制作哪些内容？','工作流程覆盖房间与导览展示内容、销售文档和营销创意。可以通过演示说明希望制作的成果，了解当前可用能力和所需支持。'],['只有户型图可以开始吗？','可以先根据户型图评估任务并梳理资料缺口。完整展示可能还需要图片、品牌素材和已确认的项目信息。'],['房间图片预览就是完整互动导览吗？','不是。图片预览只展示房间概念画面。完整导览需要对应的经审阅素材和导航，其实际操作方式应通过单独演示确认。'],['AI 画面能代表最终交付吗？','AI 画面属于概念可视化，需要对照正式项目资料审阅，并保留相应说明，不能据此确定最终规格或建成效果。'],['查看产品介绍需要安装软件吗？','不需要。通过电脑、平板或手机浏览器即可直接阅读本产品介绍页。'],['如何了解价格和使用方式？','发邮件至 hello@estatestudio.io，说明项目类型和希望制作的内容，进一步沟通当前可用的软件、制作支持与服务范围。'],['点击联系演示就完成预约了吗？','链接会打开邮件应用，请确认内容后自行发送。点击链接不代表邮件已收到，也不会自动安排会议。']],
 contactTitle:'聊聊你的地产项目。', contactBody:'告诉我们你正在准备什么、希望给谁看，一起了解 Estate Studio 如何融入你的工作。', contactNote:'打开邮件应用，无需上传文件或注册账号。', footer:'项目资料，连接创作与审阅。', concept:'AI 概念画面，不代表已核实的房产规格。', back:'回到顶部', skip:'跳转到产品介绍', inputLabel:'从资料开始', outputLabel:'到内容成果',
 }
};
