const arrow = '<span aria-hidden="true">↗</span>';
const brand = '<img src="/assets/mark.svg" alt="" width="36" height="36"><span>estate studio<span class="brand-dot">.</span></span>';
const button = (label, cls = 'button') => `<button class="${cls}" data-open="demo">${label}${arrow}</button>`;
export function render(c) {
 const roomButtons = c.rooms.map((r,i)=>`<button data-room="${i}" aria-pressed="${i===0}"><span class="room-number">0${i+1}</span>${r}</button>`).join('');
 const sheet = `<div class="paper"><div class="paper-top"><span>${c.mockEyebrow}</span><span>ES / 01</span></div><h3>${c.mockTitle}</h3><img src="/assets/living.webp" alt="${c.roomAlts[0]}" loading="lazy" width="900" height="600"><div class="paper-bottom"><span>${c.mockFooter}</span><span>↗</span></div><div class="paper-rule"></div><p>${c.mockLabel}</p></div>`;
 return `<!doctype html>
<html lang="${c.lang}"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width, initial-scale=1"><meta name="color-scheme" content="light"><title>${c.title}</title><meta name="description" content="${c.description}"><meta property="og:title" content="${c.title}"><meta property="og:description" content="${c.description}"><meta property="og:type" content="website"><meta name="robots" content="noindex,nofollow"><link rel="icon" href="/assets/mark.svg" type="image/svg+xml"><link rel="stylesheet" href="/styles.css"><link rel="preload" as="image" href="/assets/living.webp"><script type="module" src="/app.js"></script></head>
<body id="top"><a class="skip" href="#main">${c.skip}</a>
<header class="header wrap"><a class="brand" href="${c.lang==='en'?'/':'/zh/'}" aria-label="Estate Studio">${brand}</a><nav aria-label="${c.menu}"><a href="#create">${c.nav[0]}</a><a href="#workflow">${c.nav[1]}</a><a href="#faq">${c.nav[2]}</a></nav><div class="header-actions"><a class="language" href="${c.languagePath}" lang="${c.lang==='en'?'zh-CN':'en'}">${c.language}</a>${button(c.book,'button small')}</div></header>
<main id="main">
<section class="hero wrap"><div class="hero-copy"><div><p class="eyebrow"><span class="status-dot"></span>${c.eyebrow}</p><h1>${c.headline}</h1></div><div class="hero-intro"><p>${c.intro}</p><div class="hero-actions">${button(c.book)}<a class="text-link" href="#create">${c.secondary}<span aria-hidden="true">↓</span></a></div></div></div>
<div class="hero-scene"><img class="scene-image" src="/assets/living.webp" alt="${c.roomAlts[0]}" width="1800" height="1200" fetchpriority="high"><div class="scene-overlay"></div><div class="scene-top"><span class="light-label">${c.sceneTag}</span><span class="scene-index">01 / 03</span></div><div class="scene-content"><h2>${c.sceneTitle}</h2><a href="#room-preview" class="round-link" aria-label="${c.sceneAction}">↗</a></div><div class="scene-bottom"><span>${c.disclosure}</span><span class="scene-signature">ESTATE STUDIO</span></div></div><div class="hero-foot"><span>${c.heroNote}</span><span class="tiny-symbol" aria-hidden="true">⌑</span></div></section>
<div class="audience wrap"><span class="eyebrow">${c.audienceLabel}</span><div>${c.audiences.map(a=>`<span>${a}</span>`).join('')}</div></div>
<section class="section wrap" id="create"><div class="section-heading"><p class="eyebrow">${c.outputsLabel}</p><div class="heading-row"><h2>${c.outputsTitle}</h2><p>${c.outputsIntro}</p></div></div>
<article class="tour-feature" id="room-preview"><div class="room-stage"><img id="room-image" src="/assets/living.webp" alt="${c.roomAlts[0]}" width="1800" height="1200" loading="lazy"><div class="room-current"><span>${c.currentView}</span><strong id="room-label" aria-live="polite">${c.rooms[0]}</strong></div><span class="preview-tag">${c.disclosure}</span></div><div class="tour-info"><p class="eyebrow">${c.tourSmall}</p><h3>${c.tourTitle}</h3><p>${c.tourBody}</p><div class="room-switcher" role="group" aria-label="${c.controls}">${roomButtons}</div><p class="small-note">${c.viewNote}</p></div></article>
<div class="output-pair"><article class="document-feature"><button class="paper-stage" data-open="layout" aria-label="${c.docsLink}">${sheet}<span class="expand" aria-hidden="true">↗</span></button><div class="output-copy"><p class="eyebrow">${c.docsSmall}</p><h3>${c.docsTitle}</h3><p>${c.docsBody}</p><button class="text-link" data-open="layout">${c.docsLink}${arrow}</button></div></article><article class="creative-feature"><div class="poster-stage"><div class="poster"><img src="/assets/kitchen.webp" alt="${c.roomAlts[1]}" loading="lazy" width="900" height="600"><div class="poster-content"><span>${c.mockEyebrow}</span><h3>${c.posterText}</h3><span>${c.posterBottom} ↗</span></div></div><span class="poster-label">${c.mockLabel}</span></div><div class="output-copy"><p class="eyebrow">${c.creativeSmall}</p><h3>${c.creativeTitle}</h3><p>${c.creativeBody}</p>${button(c.creativeLink,'text-link')}</div></article></div></section>
<section class="why section" id="why"><div class="wrap why-grid"><div><p class="eyebrow">${c.whyLabel}</p><h2>${c.whyTitle}</h2><p class="why-intro">${c.whyIntro}</p></div><div class="benefits">${c.benefits.map((b,i)=>`<article><span class="benefit-num">0${i+1}</span><div><h3>${b[0]}</h3><p>${b[1]}</p></div></article>`).join('')}</div></div></section>
<section class="section wrap" id="workflow"><p class="eyebrow">${c.workflowLabel}</p><div class="heading-row"><h2>${c.workflowTitle}</h2><p>${c.workflowIntro}</p></div><div class="steps">${c.steps.map((s,i)=>`<article><div class="step-line"><span>0${i+1}</span><span aria-hidden="true">${i===2?'✓':'↗'}</span></div><h3>${s[0]}</h3><p>${s[1]}</p></article>`).join('')}</div><p class="workflow-note">${c.workflowNote}</p></section>
<section class="faq section wrap" id="faq"><div><p class="eyebrow">${c.faqLabel}</p><h2>${c.faqTitle}</h2></div><div class="faq-items">${c.faqs.map((f,i)=>`<details${i===0?' open':''}><summary>${f[0]}<span aria-hidden="true">+</span></summary><p>${f[1]}</p></details>`).join('')}</div></section>
<section class="contact wrap"><div class="contact-inner"><p class="eyebrow">${c.contactLabel}</p><h2>${c.contactTitle}</h2><p>${c.contactBody}</p>${button(c.book)}<p class="small-note">${c.contactNote}</p><div class="contact-email"><span>${c.emailLabel}</span><a href="mailto:hello@estatestudio.io">hello@estatestudio.io ↗</a></div></div><div class="architectural-lines" aria-hidden="true"><i></i><i></i><i></i><i></i></div></section>
</main><footer class="wrap footer"><div><a class="brand" href="#top">${brand}</a><p>${c.footerLine}</p></div><div class="footer-links"><button data-open="privacy">${c.privacy}</button><a href="mailto:hello@estatestudio.io">hello@estatestudio.io</a><a href="#top">${c.top} ↑</a></div><div class="footer-bottom"><span>© ${new Date().getFullYear()} Estate Studio</span><span>Made for property. Built around you.</span></div></footer>
<dialog id="demo" aria-labelledby="demo-title"><button class="close" data-close aria-label="${c.close}">×</button><p class="eyebrow">ESTATE STUDIO</p><h2 id="demo-title">${c.modalTitle}</h2><p>${c.modalIntro}</p><form id="demo-form"><label>${c.name}<input name="name" autocomplete="name" required maxlength="100"></label><label>${c.email}<input name="email" type="email" autocomplete="email" required maxlength="254"></label><label>${c.company}<input name="company" autocomplete="organization" maxlength="150"></label><label>${c.project}<textarea name="project" rows="3" maxlength="1200" placeholder="${c.placeholder}"></textarea></label><p class="small-note">${c.formNote}</p><button class="button" type="submit">${c.send}${arrow}</button><p id="form-feedback" role="status" hidden>${c.formFeedback}</p><a class="direct-email" href="mailto:hello@estatestudio.io">hello@estatestudio.io ↗</a></form></dialog>
<dialog id="privacy" aria-labelledby="privacy-title"><button class="close" data-close aria-label="${c.close}">×</button><h2 id="privacy-title">${c.privacyTitle}</h2><p>${c.privacyBody}</p><a class="text-link" href="mailto:hello@estatestudio.io">hello@estatestudio.io ↗</a></dialog>
<dialog id="layout" class="layout-dialog" aria-labelledby="layout-title"><button class="close" data-close aria-label="${c.close}">×</button><div><p class="eyebrow">${c.docsSmall}</p><h2 id="layout-title">${c.layoutTitle}</h2><p>${c.layoutBody}</p><p class="small-note">${c.mockCaption}</p></div>${sheet}</dialog>
<script id="page-data" type="application/json">${JSON.stringify({rooms:c.rooms,roomAlts:c.roomAlts,subject:c.mailSubject,fields:c.fieldNames}).replace(/</g,'\\u003c')}</script></body></html>`;
}
