import {escapeHtml as e,seoHead} from './seo.mjs';
const ids=['overview','audience','features','inputs','workflow','scenarios','faq'];
export function renderProduct(c,config) {
 const toc=ids.map((id,i)=>`<a href="#${id}"><span>0${i+1}</span>${e(c.labels[i])}</a>`).join('');
 const mail='mailto:hello@estatestudio.io';
 return `<!doctype html><html lang="${c.lang}"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>${e(c.title)}</title><meta name="description" content="${e(c.description)}"><meta property="og:title" content="${e(c.title)}"><meta property="og:description" content="${e(c.description)}"><meta property="og:type" content="website">${seoHead({...c,product:true},config)}<link rel="icon" href="/assets/mark.svg"><link rel="stylesheet" href="/styles.css"><link rel="stylesheet" href="/product.css"></head>
<body class="product-page" id="top"><a class="skip" href="#main">${e(c.skip)}</a><header class="header wrap"><a class="brand" href="${c.home}" aria-label="Estate Studio"><img src="/assets/mark.svg" width="36" height="36" alt=""><span>estate studio<span class="brand-dot">.</span></span></a><nav aria-label="${e(c.productLabel)}"><a href="${c.home}">${e(c.homeLabel)}</a><a href="${c.path}" aria-current="page">${e(c.productLabel)}</a><a href="#features">${e(c.labels[2])}</a></nav><div class="header-actions"><a class="language" href="${c.alternate}" lang="${c.lang==='en'?'zh-CN':'en'}">${c.language}</a><a class="button small" href="#contact">${e(c.contact)}<span aria-hidden="true">↗</span></a></div></header>
<main id="main"><section class="product-hero wrap"><nav class="breadcrumbs" aria-label="${c.lang==='en'?'Breadcrumb':'面包屑'}"><a href="${c.home}">${e(c.homeLabel)}</a><span aria-hidden="true">/</span><span aria-current="page">Estate Studio</span></nav><div class="product-hero-grid"><div><p class="eyebrow"><span class="status-dot"></span>${e(c.eyebrow)}</p><h1><span class="product-name">Estate Studio</span>${c.h1}</h1><p class="product-lead">${e(c.intro)}</p><div class="hero-actions"><a class="button" href="#features">${e(c.explore)}<span aria-hidden="true">↓</span></a><a class="text-link" href="#contact">${e(c.contact)}<span aria-hidden="true">↗</span></a></div></div><figure class="product-board"><div class="board-head"><span>ESTATE STUDIO</span><span>01 — 03</span></div><div class="board-photo"><img src="/assets/living.webp" width="1800" height="1200" alt="${c.lang==='en'?'AI concept of a living room opening onto a terrace':'通向露台的客厅 AI 概念画面'}" fetchpriority="high"><span>${e(c.outputLabels[1])}</span></div><div class="board-source"><span>${e(c.inputLabel)}</span><strong>${e(c.outputLabels[0])}</strong><span aria-hidden="true">↓</span></div><div class="board-outputs">${c.outputLabels.slice(1).map((x,i)=>`<div><span>0${i+1}</span>${e(x)}</div>`).join('')}</div><figcaption><strong>${e(c.visualTitle)}</strong><span>${e(c.visualNote)}</span></figcaption></figure></div></section>
<div class="product-body wrap"><aside class="product-toc"><details open><summary>${e(c.contents)}<span aria-hidden="true">↙</span></summary><nav aria-label="${e(c.contents)}">${toc}</nav></details><a class="toc-contact" href="${mail}">hello@estatestudio.io ↗</a></aside><article class="product-article">
<section id="overview"><p class="eyebrow">01 / ${e(c.labels[0])}</p><h2>${e(c.overviewTitle)}</h2>${c.overview.map(p=>`<p>${e(p)}</p>`).join('')}</section>
<section id="audience"><p class="eyebrow">02 / ${e(c.labels[1])}</p><h2>${e(c.audienceTitle)}</h2><div class="product-audiences">${c.audiences.map((a,i)=>`<div><span class="item-index">0${i+1}</span><h3>${e(a[0])}</h3><p>${e(a[1])}</p></div>`).join('')}</div></section>
<section id="features"><p class="eyebrow">03 / ${e(c.labels[2])}</p><h2>${e(c.featuresTitle)}</h2><p>${e(c.featuresIntro)}</p>${c.features.map((f,i)=>`<div class="product-feature"><p class="feature-kicker"><span>0${i+1}</span>${e(f[0])}</p><h3>${e(f[1])}</h3><p>${e(f[2])}</p><p class="feature-contract">${e(f[3])}</p>${i===1?`<figure class="room-evidence"><img src="/assets/kitchen.webp" alt="${c.lang==='en'?'AI concept of a kitchen and dining room':'厨房与餐厅 AI 概念画面'}" width="900" height="600" loading="lazy"><figcaption>${e(c.concept)}</figcaption></figure>`:''}</div>`).join('')}</section>
<section id="inputs"><p class="eyebrow">04 / ${e(c.labels[3])}</p><h2>${e(c.inputsTitle)}</h2><p>${e(c.inputsIntro)}</p><dl class="input-list">${c.inputs.map(x=>`<div><dt>${e(x[0])}</dt><dd>${e(x[1])}</dd></div>`).join('')}</dl></section>
<section id="workflow"><p class="eyebrow">05 / ${e(c.labels[4])}</p><h2>${e(c.workflowTitle)}</h2><ol class="product-steps">${c.steps.map(x=>`<li><h3>${e(x[0])}</h3><p>${e(x[1])}</p></li>`).join('')}</ol></section>
<section id="scenarios"><p class="eyebrow">06 / ${e(c.labels[5])}</p><h2>${e(c.scenariosTitle)}</h2><div class="scenario-grid">${c.scenarios.map((x,i)=>`<div><span class="item-index">CASE / 0${i+1}</span><h3>${e(x[0])}</h3><p>${e(x[1])}</p><p class="small-note">${e(x[2])}</p></div>`).join('')}</div></section>
<section id="faq"><p class="eyebrow">07 / ${e(c.labels[6])}</p><h2>${e(c.faqTitle)}</h2><div class="faq-items">${c.faqs.map((f,i)=>`<details${i===0?' open':''}><summary>${e(f[0])}<span aria-hidden="true">+</span></summary><p>${e(f[1])}</p></details>`).join('')}</div></section>
</article></div><section class="product-contact wrap" id="contact"><div><p class="eyebrow">ESTATE STUDIO</p><h2>${e(c.contactTitle)}</h2><p>${e(c.contactBody)}</p></div><div><a class="button" href="${mail}">hello@estatestudio.io <span aria-hidden="true">↗</span></a><p class="small-note">${e(c.contactNote)}</p></div></section></main><footer class="footer wrap"><div><a class="brand" href="${c.home}">estate studio.</a><p>${e(c.footer)}</p></div><div class="footer-links"><a href="${c.home}">${e(c.homeLabel)}</a><a href="${c.path}">${e(c.productLabel)}</a><a href="#top">${e(c.back)} ↑</a></div><div class="footer-bottom"><span>© ${new Date().getFullYear()} Estate Studio</span><span>Made for property. Built around you.</span></div></footer></body></html>`;
}
